version: '3.0'
services:
  mysql:
    image: "mysql"
    restart: "always"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./script/mysql/:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
#  redis:
#    image: "redis"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - "6379:6379"
#  etcd:
#    image: "bitnami/etcd:latest"
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#    ports:
#      - "23790:2379"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root