version: '3.0'
services:
  mysql:
    image: "mysql:8.0.19"
    restart: "always"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_DATABASE: "go-backend"
      MYSQL_PASSWORD: "root"
    volumes:
      - "./script/mysql/:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
  redis:
    image: "redis"
    restart: always
    volumes:
      - /tmp/docker/data/redis/:/data
    ports:
      - 6379:6379 # 自定义的是暴露出去的端口, Redis 容器内运行固定为 6379
    command: redis-server --requirepass root --appendonly yes
  # kafka-ui:
  #   container_name: kafka-ui
  #   image: 'provectuslabs/kafka-ui'
  #   ports:
  #     - '8888:8080'
  #   depends_on:
  #     - kafka
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: "TRUE"
  # prometheus:
  #   image: 'prom/prometheus:v2.47.2'
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - '9090:9090'
  # zipkin:
  #   image: 'openzipkin/zipkin-slim'
  #   ports:
  #     - '9411:9411'
  # grafana:
  #   image: 'grafana/grafana-enterprise'
  #   ports:
  #     - '3000:3000'
  # etcd:
  #   image: "bitnami/etcd:latest"
  #   environment:
  #     - ALLOW_NONE_AUTHENTICATION=yes
  #   ports:
  #     - "2379:2379"
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
